export default {
zhangxingcai: "敬哀皇后",

std_zhangbao: "同心并力",
	sp_liuqi: "品醇观舟",
	ol_pengyang: "翻然轻举",
	xiahouba: "棘途壮志",
	hb_fushiren: "献城投吴",
	liubei: "汉昭烈帝",
	guanyu: "四海仰鼻息",
	zhangfei: "两界大巡环使",
	zhugeliang: "人也神也",
	zhaoyun: "截江救主",

machao: "迅骛惊雷",
	huangyueying: "足智多谋",
	re_huangzhong: "定军之英",
	re_weiyan: "朔风独峙",
	pangtong: "臻华福天",
	jiangwei: "怒麟布武",
	liushan: "挤眉弄眼",
	menghuo: "南蛮王",
	zhurong: "火神之怒",
	ganfuren: "昭烈皇后",

xin_xushu: "持节不语",
	hb_jiangwanfeiyi: "群策谋策",
	old_madai: "平北将军",
	shamoke: "骁勇金衔",
	mifuren: "乱世沉香",
	xin_masu: "军略才器",
	wangping: "镇北柱国",
	xin_fazheng: "陈筹画策",
	hb_guanxing: "同心并力",
	liaohua: "御敌屏障",

guanping: "神威天降",
	jianyong: "谑浪笑敖",
	hb_koufeng: "不动如山",
	wuyi: "建兴鞍辔",
	zhangsong: "燎原之志",
	zhoucang: "忠躯义感",
	liuchen: "烈帝后裔",
	huanghao: "蛇蝎蛊心",
	guanyinping: "天骄虎女",
	maliang: "白眉智士",

mizhu: "喜挽金财",
	dongyun: "骨鲠良相",
	zhangyi: "执忠守义",
	dc_lifeng: "秋盈丰粟",
	hb_zhaotongguang: "龙威承泽",
	qinmi: "钟灵四时",
	yanyan: "拒敌之勇",
	chendao: "白毦统领",
	zhugezhan: "巍巍义烈",

hb_meifang: "负荆之臣",
	re_dengzhi: "出使东吴",
	zongyu: "九酝鸿胪",
	dc_liuba: "清河一鲲",
	yangwan: "花簇怀柔",
	yangyi: "孤鹬",
	longyufei: "将星之魂",
	pe_mengda: "求栖梧桐",

haozhao: "泼墨惊澜",
	simazhao: "堕节肇业",
	simashi: "督师定淮",
	dc_jiachong: "始作俑者",
	xiahoudun: "浴血奋战",
	zhenji: "薄幸的美人",
	xiahouyuan: "虎步关右",
	zhanghe: "百甲争魁",
	old_caoren: "坚壳之蚌",
	dianwei: "襢裼暴虎",

xunyu: "驱虎吞狼",
	caopi: "魏王称帝",
	dengai: "五谷蕃盛",
	old_re_lidian: "儒雅之风",
	caohong: "奉令西迎",
	wenpin: "镇卫江夏",
	xunyou: "扭转乾坤",
	cuimao: "直言劝谏",
	zangba: "节度青徐",
	yujin: "驰援襄樊",

niujin: "陷阵冲锋",
	zhangchunhua: "锋力染霜",
	wangyi: "笄帷贞烈",
	caochong: "飞虹云象",
	guohuai: "紫电霆击",
	manchong: "摧锋立旌",
	caozhen: "骁勇金衔",
	hanhaoshihuan: "勇往直前",
	caorui: "玺握天下",
	yangxiu: "字字珠玑",

chengyu: "素玄",
	caoang: "竭战鳞伤",
	zhugedan: "寿春举义",
	xizhicai: "墨阵千秋",
	wanglang: "凤鹛",
	xinxianying: "明辨忠奸",
	guanqiujian: "才识拔干",
	// 卡面标题字实为"斩关赴难"，与源文件名标注的"夷夏慕德"不一致，此处以卡面实际文字为准
	luzhi: "斩关赴难",
	wenyang: "陆拔山岳",
	jianggan: "千帆征战",

caoshuang: "托孤辅政",
	huaxin: "渊清玉洁",
	tianyu: "奋军镇北",
	dc_dongzhao: "奉帝于许",
	dc_yanghu: "剑影当锋",
	caomao: "向死存魏",
	caofang: "引狼入庙",
	simayi: "狼顾之像",
};
